name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
      - main # if we decide to update to the new GitHub standard
jobs:
  linux:
    name: Test and chache Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: ligolang
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix-shell --run "ligo list-declarations ./contracts/consensus.mligo"
  macOS:
    name: Test and chache macOS
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: ligolang
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix-shell --run "ligo list-declarations ./contracts/consensus.mligo"
        env:
          NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1
